version: '3.3'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production  # Change to 'development' for dev mode
    volumes:
      - .:/app  # Optional: Mount the current directory to the container for easier development

